num_led = 100
num_strips = 1

[communication]
communication_mode = 2
host = "192.168.86.53"
port = 8888
serial_port_paths = ["/dev/serial/by-id/usb-1a86_USB_Serial-if00-port0"]
baud_rate = 921600

[recording]
record_data = false
record_esp_data = false
unity_controls_recording = false
record_data_file = "record_data.vled"
record_esp_data_file = "record_esp_data.bvled"

[camera]
multi_camera = true
camera_index_1 = "2"
camera_index_2 = "0"
# video_width = 1280
# video_height = 720
no_background_frame_consumer = true

[scan]
scan_mode = 0
filter_color = 1
filter_range = 90
color_bright = 255

[unity_options]
num_container = 1
unity_ip = "127.0.0.1"
unity_ports = [5001, 5002, 5003]
unity_serial_ports = ["/dev/ttyUSB0"]
unity_serial_baudrate = 921600
unity_position_files = ["streamlined.json"]
scale = 0.08

[advanced.communication]
serial_read_timeout = 15
udp_read_timeout = 100
con_fail_limit = 2
use_queue = true
queue_size = 5
skip_confirmation = false

[advanced.camera]
no_video = true
get_events_streams_video = true
get_events_video_widgets = true
get_events_widgets_pos_index = 0
capture_frames = 0
cam2_overhead = false
cam2_overhead_flip = false

[advanced.hsv_overrides]
# [179, 101, 255] [147, 0, 255]
hsv_red_override = [0, 0, 245, 18, 72, 255]
hsv_green_override = [62, 11, 196, 79, 58, 255]
hsv_blue_override = [61, 0, 245, 95, 255, 255]

[advanced.transform]
# crop_override = [0, 0, 1280, 720]

[advanced.misc]
print_send_back = false
no_controller = false
